//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiningPhilosophers.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiningPhilosophers.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string AlgorithmTextBracket {
            get {
                return ResourceManager.GetString("AlgorithmTextBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eat();.
        /// </summary>
        internal static string AlgorithmTextEat {
            get {
                return ResourceManager.GetString("AlgorithmTextEat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to else {.
        /// </summary>
        internal static string AlgorithmTextElse {
            get {
                return ResourceManager.GetString("AlgorithmTextElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if (fork == left) {.
        /// </summary>
        internal static string AlgorithmTextIsEqualLeft {
            get {
                return ResourceManager.GetString("AlgorithmTextIsEqualLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to while ( !left_fork_free) {.
        /// </summary>
        internal static string AlgorithmTextIsLeftFree {
            get {
                return ResourceManager.GetString("AlgorithmTextIsLeftFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to while ( !right_fork_free) {.
        /// </summary>
        internal static string AlgorithmTextIsRightFree {
            get {
                return ResourceManager.GetString("AlgorithmTextIsRightFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to put_forks();.
        /// </summary>
        internal static string AlgorithmTextPut {
            get {
                return ResourceManager.GetString("AlgorithmTextPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fork = get_random_fork();.
        /// </summary>
        internal static string AlgorithmTextRandom {
            get {
                return ResourceManager.GetString("AlgorithmTextRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to take_left_fork();.
        /// </summary>
        internal static string AlgorithmTextTakeLeft {
            get {
                return ResourceManager.GetString("AlgorithmTextTakeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to take_right_fork();.
        /// </summary>
        internal static string AlgorithmTextTakeRight {
            get {
                return ResourceManager.GetString("AlgorithmTextTakeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    wait();.
        /// </summary>
        internal static string AlgorithmTextWait {
            get {
                return ResourceManager.GetString("AlgorithmTextWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматический режим.
        /// </summary>
        internal static string ButtonAutomaticModeStart {
            get {
                return ResourceManager.GetString("ButtonAutomaticModeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить.
        /// </summary>
        internal static string ButtonAutomaticModeStop {
            get {
                return ResourceManager.GetString("ButtonAutomaticModeStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение не удалось.
        /// </summary>
        internal static string FileSaveError {
            get {
                return ResourceManager.GetString("FileSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.11.3
        /// * http://jquery.com/
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// *
        /// * Copyright 2005, 2014 jQuery Foundation, Inc. and other contributors
        /// * Released under the MIT license
        /// * http://jquery.org/license
        /// *
        /// * Date: 2015-04-28T16:19Z
        /// */
        ///
        ///(function( global, factory ) {
        ///
        ///	if ( typeof module === &quot;object&quot; &amp;&amp; typeof module.exports === &quot;object&quot; ) {
        ///		// For CommonJS and CommonJS-like environments where a proper window is present,
        ///		// execute the factory and get jQuer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_11_3 {
            get {
                return ResourceManager.GetString("jquery_1_11_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Dining philosophers&lt;/title&gt;
        ///    &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;style.css&quot;/&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;jquery-1.11.3.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;
        ///        $(document).ready(function () {
        ///            var f1p1Top = &quot;+=70px&quot;;
        ///            var f1p1Left = &quot;+=10px&quot;;
        ///            var f1p2Top = &quot;+=40px&quot;;
        ///            var f1p2Left = &quot;+=60px&quot;;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PhilosophersTable {
            get {
                return ResourceManager.GetString("PhilosophersTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///    margin: 0;
        ///    padding: 0;
        ///    background: RGB(240, 240, 240);
        ///}
        ///body div {
        ///    width: 200px;
        ///    margin: auto;
        ///}
        ///.phil, span {
        ///    position: relative;
        ///    width: 50px;
        ///}
        ///.fork {position: relative; }
        ///#table {
        ///    margin-top: -200px;
        ///    width: 200px;
        ///}
        ///.phil, .fork {
        ///    position:relative;
        ///}
        ///#p1 { left: 55px; top: 260px }
        ///#p2 { left: 120px; top: 200px; }
        ///#p3 { left: 65px; top: 50px; }
        ///#p4 { left: -50px; top: -10px; }
        ///#p5 { left: -105px; top: 140px; }
        ///#ptext1 { top: 110px [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Больой {
            get {
                object obj = ResourceManager.GetObject("Больой", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Вилка {
            get {
                object obj = ResourceManager.GetObject("Вилка", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Вилка1 {
            get {
                object obj = ResourceManager.GetObject("Вилка1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Вилка2 {
            get {
                object obj = ResourceManager.GetObject("Вилка2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Вилка3 {
            get {
                object obj = ResourceManager.GetObject("Вилка3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Вилка4 {
            get {
                object obj = ResourceManager.GetObject("Вилка4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Вилка5 {
            get {
                object obj = ResourceManager.GetObject("Вилка5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Малый {
            get {
                object obj = ResourceManager.GetObject("Малый", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
